### ISSUE TITLE
Make prefixes and suffixes customizable

### ISSUE THREAD

**Issue by robbporto** [robbporto/reshort#1]
Right now, only one prefix (`GET_`) and two suffixes (`_SUCCESSFUL`) and (`_FAILURE`) exist and they are hard-coded.

Make it customizable so it's possible to define prefixes/suffixes.

**Comment by jhia** [comment]
Considering changing the to Object-Oriented, changing `typesOfConstants` to a method?
Or maybe adding an optional argument to `makeCompleteAction`?

**Comment by robbporto** [comment]
Hi, @jhia!

What I was thinking was creating an `options` argument in the `makeCompleteAction`, so we could do something like this:

```javascript
const productsActions = reshort("Products", {
  prefix: "FETCH",
  successSuffix: "SUCCESS",
  errorSuffix: "FAIL"
});
```

This way we can add more options in the future if needed to.

**Comment by lucianomlima** [comment]
Prefix and suffix can be passed as optional argument when call `productsActions`. This way you can have actions like `FETCH_PRODUCT_SUCCESS`, `SET_PRODUCT_DETAILS`, `GET_PRODUCT`.

Prefix can have a default value and suffix will be undefined.

**Comment by robbporto** [comment]
That's I thought at first but I think that it could become a little bit verbose?

Let's say that you have three product actions (created using `reshort("Products")`). I think that's easier to define the prefixes and suffixes of these three actions in one place than to define in three different places.

Did you get what I'm saying here?

**Comment by tharyckgusmao** [comment]
Prefixos customizados seria o esquema. Vai ficar show demaiss !!

**Comment by robbporto** [comment]
I'm on it!
